Lint errors resolve

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -83,7 +83,7 @@ jobs:
 
       - name: Extract Go Modules Cache
         run: |
-          tar -xzf /path/to/cache.tar.gz || echo "Warning: Failed to extract cache"
+          tar -xzf usr/bin/tar/cache.tar.gz || echo "Warning: Failed to extract cache"
 
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v3
@@ -144,7 +144,7 @@ jobs:
 
       - name: Extract Go Modules Cache
         run: |
-          tar -xzf /path/to/cache.tar.gz || echo "Warning: Failed to extract cache"
+          tar -xzf usr/bin/tar/cache.tar.gz || echo "Warning: Failed to extract cache"
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
